Repository Roboy/roboy_dialog, pull requests merged in 2018-07, with the labels that each got.

#52 Wagram Said I should PR this :)
  dialog/src/main/java/roboy/dialog/DialogSystem.java
Labels: bug

#63 Botboy dev
  README.md
  config.properties
  dialog/src/main/java/roboy/dialog/Conversation.java
  dialog/src/main/java/roboy/dialog/ConversationManager.java
  dialog/src/main/java/roboy/dialog/tutorials/tutorialStates/DoYouKnowMathState.java
  dialog/src/main/java/roboy/io/TelegramOutput.java
  dialog/src/main/java/roboy/util/ConfigManager.java
  docs/Project_Structure/1_Tutorials.rst
  docs/Project_Structure/2_Code_Structure_overview.rst
  docs/Project_Structure/5_Libraries.rst
  docs/System_Architecture/0_Overview.rst
  docs/System_Architecture/1_Core.rst
  docs/Usage/0_installation.rst
  docs/Usage/1_getting_started.rst
  docs/conf.py
  docs/developer_manual/0_Documentation Guidelines.rst
  docs/developer_manual/1_Tutorials.rst
  docs/developer_manual/2_Code_Structure_overview.rst
  docs/developer_manual/3_API.rst
  docs/developer_manual/4_Resources.rst
  docs/developer_manual/5_Libraries.rst
  docs/developer_manual/images/PARSER_arch.png
  docs/developer_manual/images/toy_personality.png
  docs/index.rst
  docs/system_architecture/0_Overview.rst
  docs/system_architecture/1_Core.rst
  docs/system_architecture/2_Conversation.rst
  docs/system_architecture/3_World_Interfaces.rst
  docs/system_architecture/images/DialogSystem_Conversation.png
  docs/system_architecture/images/DialogSystem_Core.png
  docs/system_architecture/images/DialogSystem_World_Interfaces.png
  docs/system_architecture/images/architecture_diagram.drawio.xml
  docs/system_architecture/images/architecture_diagram.png
  docs/system_architecture/images/architecture_diagram_simplified.drawio.xml
  docs/system_architecture/images/architecture_diagram_simplified.png
  docs/system_architecture/images/context.png
  docs/system_architecture/images/ordinary_personality.png
  docs/system_architecture/images/parser.png
  docs/user_manual/0_installation.rst
  docs/user_manual/1_getting_started.rst
  docs/user_manual/2_configuration.rst
Labels: bug, enhancement

#64 Deprecation of Simple Tokenizer
  dialog/src/main/java/roboy/dialog/ConversationManager.java
  dialog/src/main/java/roboy/linguistics/sentenceanalysis/SimpleTokenizer.java
Labels: dialog-evolution, enhancement
